config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations' }
  root to: 'pages#home'
  get '/about', to: 'pages#about'
  get '/about/download_pdf', to: 'pages#download_pdf'
  resources :offers
  resources :projects do
    resources :orders
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contractor.rb
class Contractor < ActiveRecord::Base
    
  has_many :users
  has_many :projects
end

app/models/offer.rb
class Offer < ActiveRecord::Base
  validates :client_name, presence: true
  validates :email, presence: true
  validates :order_description, presence: true
end

app/models/order.rb
class Order < ActiveRecord::Base
  
  validates :n_workers_male, presence: true, numericality: { only_integer: true }
  validates :n_workers_female, presence: true,  numericality: { only_integer: true }
  validates :n_office_staff, presence: true, numericality: { only_integer: true }
    
  belongs_to :project
    
end

app/models/project.rb
class Project < ActiveRecord::Base
    
  has_many :orders
  has_one_attached :avatar
  belongs_to :contractor
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  belongs_to :contractor
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/offers_controller.rb
class OffersController < ApplicationController
  
  # GET request to /offers/new
  # Show new contact form
  def new
    @offer = Offer.new
  end
  
  # POST request to /offers
  def create
    # Mass assignment of form fields into Offer object
    @offer = Offer.new(offer_params)
    # Save the Offer object to the database
    if @offer.save
      # Store form fields via paramaters into variables
      name = params[:offer][:client_name]
      email = params[:offer][:email]
      mobile = params[:offer][:mobile]
      delivery_address = params[:offer][:delivery_address]
      postcode = params[:offer][:postcode]
      description = params[:offer][:order_description]
      comments = params[:offer][:comments]
      # Plug variables into Contact Mailer email method
      # and send email
      OfferMailer.offer_email(name, email, mobile, delivery_address, postcode, description, comments).deliver
       # Redirect to the "new" action
       flash[:success] = "Message Sent!"
      redirect_to new_offer_path
    else
      # If Offer object doesn't save
      # redirect to the "new" action
      flash[:error] = @offer.errors.full_messages.join(", ")
      redirect_to new_offer_path
    end
  end
  
  def index
  end
  
  def show
    @offer = Offer.find_by(id: params[:id])
    if @offer.nil?
        redirect_to offers_path
    end
  end
  
  private
    # To collect data from forms
    # we need to use stron parameters
    # and whitelist form fields
    def offer_params
      params.require(:offer).permit(:client_name, :email, :mobile, :delivery_address, :postcode, :order_description, :comments)
    end
    
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
    
  def new
    @order = Order.new
  end
  
  def create
    # Ensure that we have the user who is filling out the form
    @project = Project.find( params[:project_id] )
    # Create profile linked to this specific user
    @order = @project.orders.build( order_params )
    if @order.save
      flash[:success] = "Order Saved"
      redirect_to project_path( params[:project_id] )
    else
      flash[:error] = @order.errors.full_messages.join(", ")
      redirect_to new_project_orders_path( params[:project_id] )
    end
  end
  
  def show
    @order = Order.find( params[:id] )
  end
  
  private
  def order_params
    params.require(:order).permit(:n_workers_male, :n_workers_female, :n_office_staff)
  end
  
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
  
  def about
  end
  
  def download_pdf
    send_file(
      "#{Rails.root}/public/Select Brochure.pdf",
      filename: "Select_Brochure.pdf",
      type: "application/pdf"
    )
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
    
    def new
        @project = Project.new
    end
    
    def create
        @contractor = current_user.contractor
        @project = @contractor.projects.build( project_params )
        @project.contact = "#{current_user.first_name}" + " " + "#{current_user.last_name}"
        if @project.save
            redirect_to projects_path
        else
            flash[:error] = @project.errors.full_messages.join(", ")
            redirect_to new_project_path
        end
    end
    
    def index
    end
    
    def show
        @project = Project.find_by(id: params[:id])
    end
    
    private
        def project_params
            params.require(:project).permit(:name, :avatar)
        end

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  
  private
  
  def sign_up_params
    params.require(:user).permit(:first_name, :last_name, :email, :contractor_id, :password, :password_confirmation)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Oaf</title>
    <%= csrf_meta_tags %>
    <link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <%= link_to root_path, class: "navbar-brand" do %>
        Select
      <% end %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav">
          <li class="nav-item">
            <%= link_to "About", about_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Pricing</a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Offer Section
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
              <%= link_to "Offers", offers_path, class:"dropdown-item" %>
              <%= link_to "Offer Form", new_offer_path, class: "dropdown-item" %>
            </div>
          </li>
          <% if user_signed_in? %>
            <% if current_user.contractor_id == 3 %>
              <li class="nav-item dropdown active">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Projects
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                  <%= link_to "Projects", projects_path, class:"dropdown-item" %>
                  <%= link_to "New Project", new_project_path, class:"dropdown-item" %>
                </div>
              <% end %>
            <% end %>
          </li>
        </ul>
        <div class="nav navbar-nav ml-auto">
          <% if user_signed_in? %>
            <%= link_to "Log Out", destroy_user_session_path, method: :delete, class: "btn btn-default navbar-btn" %>
          <% else %>
            <%= link_to "Log In", new_user_session_path, class: "btn btn-default navbar-btn" %>
            <%= link_to "Sign Up", new_user_registration_path, class: "btn btn-default navbar-btn" %>
          <% end %>
        </div>
      </div>
    </nav>
    
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/offers/index.html.erb
<h1>Enquiries:</h1>

<table class="table">
  <thead>
    <tr>
      <th scope="col">Name</th>
      <th scope="col">Email</th>
      <th scope="col">Order Details</th>
      <th scope="col">Comments</th>
    </tr>
  </thead>
  <tbody>
    <% Offer.all.each do |offer| %>
      <tr>
        <th scope="row"><%= "#{ offer[:client_name] }" %></th>
        <td><%= "#{ offer[:email] }" %></td>
        <td><%= "#{ offer[:order_description] }" %></td>
        <td><%= "#{ offer[:comments] }" %></td>
        <td><%= link_to "View", offer_path(offer), class: "btn btn-primary" %></td>
        <td><%= link_to "Delete", "#", class: "btn btn-danger" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/offers/new.html.erb
<!DOCTYPE html>

<h3 class="text-center">Offer Form</h3>    
  
<%= flash[:error] %>
<div class="well">
  <%= form_for @offer do |f| %>
    <div class="form-row">
      <div class="form-group col-md-4">
        <%= f.label :client_name %>
        <%= f.text_field :client_name, class: 'form-control' %>
      </div>
      <div class="form-group col-md-4">
        <%= f.label :email %>
        <%= f.text_field :email, class: 'form-control' %>
      </div>
      <div class="form-group col-md-4">
        <%= f.label :mobile %>
        <%= f.text_field :mobile, class: 'form-control' %>
      </div>
    </div>
    
    <div class="form-row">
      <div class="form-group col-md-8">
        <%= f.label :delivery_address %>
        <%= f.text_field :delivery_address, class: 'form-control' %>
      </div>
      <div class="form-group col-md-4">
        <%= f.label :postcode %>
        <%= f.text_field :postcode, class: 'form-control' %>
      </div>
    </div>
    
    <div class="form-group">
      <%= f.label :order_description %>
      <%= f.text_field :order_description, class: 'form-control' %>
    </div>
  
    <div class="form-group">
      <%= f.label :comments %>
      <%= f.text_field :comments, class: 'form-control' %>
    </div>

      <%= f.submit 'Submit', class: 'btn btn-default' %>
  <% end %>
</div>

app/views/offers/show.html.erb
<div class="row">
  <div class="col-sm-8">
    <h1 align="center"><%= @offer[:client_name] %></h1>
  </div>
</div>
<div class="row">
  <div class="col-sm-4">
    <div class="well">
      <h5>Email Address</h5>
      <p><%= @offer[:email] %></p>
    </div>
  </div>
  <div class="col-sm-3">
    <div class="well">
      <h5>Mobile Number</h5>
      <p><%= @offer[:mobile] %></p>
    </div>
  </div>
  <div class="col-sm-5">
    <div class="well">
      <h5>Address</h5>
      <p><%= @offer[:delivery_address] %></p>
      <p><%= @offer[:postcode] %></p>
    </div>
  </div>
</div>
<div class="row">
  <div class="col-sm-8">
    <div class="well">
      <h5>Order Description</h5>
      <p><%= @offer[:order_description] %></p>
    </div>
  </div>
  <div class="col-sm-4">
    <div class="well">
      <h5>Comments</h5>
      <p><%= @offer[:comments] %></p>
    </div>
  </div>
</div>

app/views/orders/_summaryTable.html.erb
<table class="table table-responsive table-hover">
  <thead>
    <tr>
      <th scope="col">No</th>
      <th scope="col" colspan="4">Description</th>
      <th scope="col">Price</th>
    </tr>
  </thead>
  <tbody>
    <tr class="clickable" data-toggle="collapse" data-target="#group-of-rows-1" aria-expanded="flase" aria-controls="group-of-rows-1">
      <td>1</td>
      <td colspan="4"> Upfront costs for preparation</td>
      <td>£40000.00</td>
    </tr>
    <tr id="group-of-rows-1" class="collapse">
      <td colspan="6">
        Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod. Brunch 3 wolf moon tempor, sunt aliqua put a bird on it squid single-origin coffee nulla assumenda shoreditch et. Nihil anim keffiyeh helvetica, craft beer labore wes anderson cred nesciunt sapiente ea proident. Ad vegan excepteur butcher vice lomo. Leggings occaecat craft beer farm-to-table, raw denim aesthetic synth nesciunt you probably haven't heard of them accusamus labore sustainable VHS.
      </td>
    </tr>
    <tr>
      <td>2</td>
      <td colspan="4">Modular Unit Ancillary Upgrades</td>
      <td> - </td>
    </tr>
    <tr>
      <td>3</td>
      <td colspan="4">Installation</td>
      <td>£10000.00</td>
    </tr>
    <tr>
      <td>4</td>
      <td colspan="4">Craneage</td>
      <td>£2667.00</td>
    </tr>
    <tr class="clickable" data-toggle="collapse" data-target="#group-of-rows-5" aria-expanded="flase" aria-controls="group-of-rows-5">
      <td>5</td>
      <td colspan="4">Furniture</td>
      <td>£20000.00</td>
    </tr>
    <tr id="group-of-rows-5" class="collapse">
      <td></td>
      <td><h6>Ground Floor</h6></td>
      <td>No. </td>
      <td>Individual Price</td>
      <td>Total Price</td>
    </tr>
    <tr id="group-of-rows-5" class="collapse">
      <td></td>
      <td>Double Wire Cage Locker</td>
      <td>36</td>
      <td>£<%= 9600/36 %>.00</td>
      <td>£9600.00</td>
    </tr>
    <tr id="group-of-rows-5" class="collapse">
      <td></td>
      <td>Single Wire Cage Locker</td>
      <td>2</td>
      <td>£120.00</td>
      <td>£240.00</td>
    </tr>
  </tbody>
</table>

app/views/orders/new.html.erb
<h3 class="text-center">New Order</h3>

<%= flash[:error] %>
<div class="well">
  <%= form_for @order, url: project_orders_path do |f| %>
    <div class="form-row">
      <div class="form-group col-md-3">
        <%= f.label :male_site_operatives %>
        <%= f.text_field :n_workers_male, class: "form-control" %>
      </div>
      <div class="form-group col-md-3">
        <%= f.label :female_site_operatives %>
        <%= f.text_field :n_workers_female, class: "form-control" %>
      </div>
      <div class="form-group col-md-3">
        <%= f.label :number_of_office_staff %>
        <%= f.text_field :n_office_staff, class: "form-control" %>
      </div>
      <!--<div class="form-group col-md-3">-->
      <!--  <%= f.label :female_office_staff %>-->
      <!--  <%= f.text_field :n_office_staff, class: "form-control" %>-->
      <!--</div>-->
    </div>
    
    <%= f.submit 'Place Order', class: 'btn btn-default' %>
    
  <% end %>
</div>

app/views/orders/show.html.erb
<h1>Order <%= @order.id %></h1>

<nav>
  <div class="nav nav-tabs" id="orderComponentTabs" role="tablist">
    <a class="nav-item nav-link active" id="nav-summary-tab" data-toggle="tab" href="#nav-summary" role="tab" aria-controlls="nav-summary" aria-selected="true">Job Costing</a>
    <a class="nav-item nav-link" id="nav-preparation-tab" data-toggle="tab" href="#nav-preparation" role="tab" aria-controlls="nav-preparation" aria-selected="false">Technical Drawings</a>
    <a class="nav-item nav-link" id="nav-installation-tab" data-toggle="tab" href="#nav-installation" role="tab" aria-controlls="nav-installation" aria-selected="false">Programme of Works</a>
  </div>
</nav>
<div class="tab-content" id="orderComponentTabsContent">
  <div class="tab-pane fade show active" id="nav-summary" role="tabpane1" aria-labelledby="nav-summary-tab">
    <%= render 'summaryTable' %>
  </div>
  <div class="tab-pane fade" id="nav-preparation" role="tabpane1" aria-labelledby="nav-preparation-tab">
    Technical Drawings would go here
  </div>
  <div class="tab-pane fade" id="nav-installation" role="tabpane1" aria-labelledby="nav-installation-tab">
    Programme of Works here
  </div>
</div>

app/views/pages/about.html.erb
About Page

<%= link_to 'Download Select Brochure', about_download_pdf_path %>

app/views/pages/home.html.erb
<h1>Homepage</h1>

<% if user_signed_in? %>
  <div class="card-deck">
    <% Project.all.each do |project| %>
      <% if project.contractor_id == current_user.contractor_id %>
        <div class="card">
          <dev class="card-body">
            <h5 class="card-title"><%= project.name %></h5>
            <h6 class="card-subtitle mb-2 text-muted"><%= project.contractor.name %></h6>
            <p class="card-text">Example text to build on the card title and make up the bulk of the card's content</p>
            <%= link_to "View", project_path(project), class: "btn btn-primary" %>
          </dev>
        </div>
      <% end %>
    <% end %>
  </div>
<% else %>
  <p>This Website is for test purposes only.</p>
<% end %>

<% if user_signed_in? %>
  <% if current_user.contractor.name == "Select" %>
    <h5>To Do:</h5>
  <% end %>
<% end %>

app/views/projects/index.html.erb
<h1>Projects:</h1>

<table class="table">
  <thead>
    <tr>
      <th scope="col">Name</th>
      <th scope="col">Contractor</th>
      <th scope="col">Contact</th>
    </tr>
  </thead>
  <tbody>
    <% Project.all.each do |project| %>
      <tr>
        <th scope="row"><%= "#{ project.name }" %></th>
        <% if project.contractor_id? %>
          <td><%= "#{ project.contractor.name }" %></td>
        <% else %>
          <td> - </td>
        <% end %>
        <td><%= "#{ project.contact }" %></td>
        <td><%= link_to "View", project_path(project), class: "btn btn-primary" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/projects/new.html.erb
<!DOCTYPE html>

<h3 class="text-center">New Project</h3>    
  
<%= flash[:error] %>
<div class="well">
  <%= form_for @project do |f| %>
    <div class="form-row">
      <div class="form-group col-md-4">
        <%= f.label :project_name %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>
      <div class="form-group col-md-4">
        <%= f.label :avatar %>
        <%= f.file_field :avatar, class: 'form-control' %>
      </div>
    </div>

      <%= f.submit 'Submit', class: 'btn btn-default' %>
  <% end %>
</div>

app/views/projects/show.html.erb
<div class="jumbotron jumbotron-fluid">
  <div class="container">
    <h1 class="display-4"><%= @project.name %></h1>
    <h5><%= @project.contractor.name %></h5>
    <p class="lead"><%= @project.contact %></p>
  </div>
</div>

<% @project.orders.all.each do |order| %>
  <div class="card">
    <div class="card-header">
      <%= "Order ID: #{order[:id]}" %>
    </div>
    <div class="card-body">
      <p class="card-text"><%= "Workers: #{order[:n_workers_female] + order[:n_workers_male]}"%></p>
      <p class="card-text"><%= "Office Staff: #{order[:n_office_staff]}"%></p>
      <p class="card-text"><%= "Price: £#{order[:price]}"%></p>
      <%= link_to "View", project_order_path(project_id: @project.id, id: order.id), class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

<%= link_to "New Order", new_project_order_path(project_id: @project.id), class: "btn btn-primary" %>